[package]
name = "oneof"
version = "0.1.0"
edition = "2024"
authors = ["EluvK <eluvk.dev@gmail.com>"]
description = "derive(OneOf) to ensure exactly one Option<_> field is Some"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
